application: box-man
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: fonts

- url: /.*
  script: main.app

- url: /admin/.*
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
